# Generated by Django 2.0.2 on 2018-03-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='account',
        ),
    ]
